<@s.set name="user" value="#session.user" />
	<td class="left_menu">
			<#-- DISPLAY MAIN MENU -->
		<div class="bold menu_link"> <a href="<@s.url namespace="/" action="selected-topics" />">Home</a> </div>
		<div class="menu_link"> <a href="<@s.url namespace="/" action="browse"/>">Browse</a> </div>
<@s.if test="#user != null">
		<div class="menu_link"> &nbsp; </div>
		<div class="menu_hdr"> Tools </div>
	<@s.if test="#user.admin">
		<div class="menu_link"> <a href="<@s.url namespace="/admin" action="home" />">Admin</a> </div>
		<div class="menu_link"> <a href="<@s.url namespace="/forms" action="change-password" />">Change Password</a> </div>
	</@s.if>
	<@s.else>
		<#if !user.issues.empty>
		<div class="menu_link"> <a href="<@s.url namespace="/my-account" action="home" />">My Issues</a> </div>
    </#if>
		<div class="menu_link"> <a href="<@s.url namespace="/my-account" action="edit-profile" />">Edit Issues</a> </div>
		<div class="menu_link"> <a href="<@s.url namespace="/forms" action="change-password" />">Change Password</a> </div>
		<#if !user.issues.empty>
		<div class="menu_link"> <a href="<@s.url namespace="/forms" action="browse-sources" />">Browse by Source</a> </div>
    </#if>
<#--	<div class="menu_link"> <a href="<@s.url namespace="/news" action="download" />">Download News</a> </div> -->
<#--	<div class="menu_link"> <a href="<@s.url namespace="/news" action="reclassify" />Classify from Archives</a> </div> -->
<#--	<div class="menu_link"> <a href="<@s.url namespace="/" action="search" />Search</a> </div> -->
	</@s.else>
</@s.if>
<@s.else>
		<div class="menu_link"> <a href="<@s.url namespace="/forms" action="login" />">Sign In</a> </div>
		<div class="menu_link"> <a href="<@s.url namespace="/forms" action="register" />">Register</a> </div>
<#--<div class="menu_link"> <a href="<@s.url namespace="/forms" action="search" />Search</a> </div> -->
</@s.else>
		<div class="menu_link"> &nbsp; </div>

<#--
 # Display the list of issues
 # Possible scenarios
 # 1. There is no active profile ==> nothing to be displayed
 # 2. Active profile exists, but, is not yet validated ==> Display message
 # 3. Active validated profile exists ==> Display issues
 # -->
<@s.if test="#user && !#user.admin">
	    <#-- HELP MENU -->
		<div class="menu_hdr"> Help </div>
<#--	<div class="menu_link"> <a class="helplink" href="<@s.url namespace="/help" action="help" />">Help</a> </div> -->
		<div class="menu_link"> <a class="helplink" target="_blank" href="<@s.url namespace="/help" action="user-guide" />">User Guide</a> </div>
		<div class="menu_link"> &nbsp; </div>
</@s.if>
		<div class="menu_hdr"> About </div>
		<div class="menu_link"> <a href="<@s.url namespace="/about" action="about" />">About</a> </div>
		<div class="menu_link"> <a href="<@s.url namespace="/about" action="faq" />">FAQ</a> </div>
		<div class="menu_link"> <a href="<@s.url namespace="/about" action="testimonials" />">Awards, Articles, Testimonials</a> </div>
		<div class="menu_link"> <a href="<@s.url namespace="/about" action="disclaimer" />">Disclaimer</a> </div>
		<div class="menu_link"> <a href="<@s.url namespace="/about" action="credits" />">Credits</a> </div>
		<div class="menu_link"> <a href="<@s.url namespace="/about" action="contact" />">Contact</a> </div>
		<div class="menu_link"> &nbsp; </div>

			<#-- Extras MENU -->
		<div class="menu_hdr"> Extras </div>
		<div class="menu_link"> <a href="<@s.url namespace="/extras" action="crawled-feeds" />">RSS feeds generated by NewsRack</a> </div>
		<div> &nbsp; </div>
		<div class="menu_link"> <a href="<@s.url namespace="/extras" action="known-indian-feeds" />">Known RSS feeds of Indian papers</a> </div>
	</td>
